AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "db/migrate/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "spec/fixtures/**/*"
    - "Gemfile"

plugins:
  - rubocop-rails
  - rubocop-rspec

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/IndentationWidth:
  Width: 2

Lint/UselessAssignment:
  Enabled: true

RSpec/SpecFilePathFormat:
  Enabled: true

RSpec/SpecFilePathSuffix:
  Enabled: true

RSpec/MultipleExpectations:
  Enabled: false
